In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [3]:
X ,y = load_diabetes(return_X_y= True)

In [4]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
X.shape

(442, 10)

In [6]:
y.shape

(442,)

Using sklearn linear regression

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train ,y_test = train_test_split(X,y,test_size=0.2 , random_state=42)

In [8]:
from sklearn.linear_model import LinearRegression
le = LinearRegression()
le.fit(X_train,y_train)
y_pred = le.predict(X_test)

In [10]:
print(y_test )

[219.  70. 202. 230. 111.  84. 242. 272.  94.  96.  94. 252.  99. 297.
 135.  67. 295. 264. 170. 275. 310.  64. 128. 232. 129. 118. 263.  77.
  48. 107. 140. 113.  90. 164. 180. 233.  42.  84. 172.  63.  48. 108.
 156. 168.  90.  52. 200.  87.  90. 258. 136. 158.  69.  72. 171.  95.
  72. 151. 168.  60. 122.  52. 187. 102. 214. 248. 181. 110. 140. 202.
 101. 222. 281.  61.  89.  91. 186. 220. 237. 233.  68. 190.  96.  72.
 153.  98.  37.  63. 184.]


In [11]:
print(y_pred)

[139.5475584  179.51720835 134.03875572 291.41702925 123.78965872
  92.1723465  258.23238899 181.33732057  90.22411311 108.63375858
  94.13865744 168.43486358  53.5047888  206.63081659 100.12925869
 130.66657085 219.53071499 250.7803234  196.3688346  218.57511815
 207.35050182  88.48340941  70.43285917 188.95914235 154.8868162
 159.36170122 188.31263363 180.39094033  47.99046561 108.97453871
 174.77897633  86.36406656 132.95761215 184.53819483 173.83220911
 190.35858492 124.4156176  119.65110656 147.95168682  59.05405241
  71.62331856 107.68284704 165.45365458 155.00975931 171.04799096
  61.45761356  71.66672581 114.96732206  51.57975523 167.57599528
 152.52291955  62.95568515 103.49741722 109.20751489 175.64118426
 154.60296242  94.41704366 210.74209145 120.2566205   77.61585399
 187.93203995 206.49337474 140.63167076 105.59678023 130.70432536
 202.18534537 171.13039501 164.91423047 124.72472569 144.81030894
 181.99635452 199.41369642 234.21436188 145.95665512  79.86703276
 157.369412

In [13]:
from sklearn.metrics import r2_score , mean_squared_error
r2c = r2_score(y_test,y_pred)
r2c

0.4526027629719195

In [14]:
le.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [15]:
le.intercept_

np.float64(151.34560453985995)

Making our own Linear regression class 


In [ ]:
class LR :
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        np.insert(X_train,0,1,axis=1)

        # calculate the coeff 
        betas =  np.linalg.inv(np.dot(X_train.T,X_train)).dot( X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ =betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [28]:
lr = LR()



In [29]:
lr.fit(X_train,y_train)

In [30]:
X_train.shape

(353, 10)

In [31]:
lr.predict(X_test)
r2c = r2_score(y_test,y_pred)

In [32]:
r2c

0.4526027629719195

In [33]:
lr.coef_

array([-258.20102769,  627.48724557,  346.3131022 , -803.34876809,
        312.91593062,   45.12316433,  211.9889459 ,  700.88175104,
        144.68714213])

In [35]:
lr.intercept_

np.float64(125.2102946862093)